### ISSUE TITLE
TabView example

### ISSUE THREAD

**Issue by veedeo** [akveo/kittenTricks#17]
How about cool looking TabView example, with swipe and TabNavigator support?

**Comment by malashkevich** [comment]
Hi @veedeo!
Do you mean more close integration `RkTabView` with `TabNavigator` from `react-navigation`?
Actually this two components has a different meaning: `RkTabView` usually used on one screen in order to show different information about one subject. `TabNavigator` is navigation pattern used to switch between different views.

You can always create custom `tabBarComponent` for `TabNavigator` using our components. It should work well.

**Comment by veedeo** [comment]
Now I understand. Anyway can you add tabs to kittenTricks so it will be
complete themed example

**Comment by malashkevich** [comment]
That's good idea! Thank you!
I will add this to roadmap.

**Comment by Paul-Todd** [comment]
You can probably reuse the code from https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js
