### ISSUE TITLE
Need Help : "dose not exist in the Haste module map"

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#191]
Hello, 

I'm making an app using the kittenTricks package and I'm following the structure just like your demo app but I'm facing the issue below ... Please help.

**Already tried**

npm run start:prod
npm start --reset-cache
#171

**My Application Link**
https://github.com/IAmAbhishekTomar/quibik

**ERROR**
```
Unable to resolve "@src/core/themes" from "src/app.component.tsx"
Failed building JavaScript bundle.
```
![WhatsApp Image 2019-06-24 at 3 22 34 AM](https://user-images.githubusercontent.com/6933841/59980931-698d2d80-962f-11e9-972c-e667a82845d3.jpeg)

**Comment by artyorsh** [comment]
This is unable to resolve because you don't completely follow the structure. We do some tricks to enable path aliasing with creating a `package.json` for "root" directories. We don't recommend to do this, so you need to replace `@src/core/themes` with an absolute path or setup other way of resolving modules with a [resolver plugin](https://github.com/tleunen/babel-plugin-module-resolver)
We also [have an example](https://github.com/akveo/kittenTricks/blob/master/babel.config.js#L10) of using this plugin in app, so simply follow plugin documentation to get this working

**Comment by ImAbhishekTomar** [comment]
You are rocks!!!! 🤘🤘👍👍
Thanks @artyorsh
