### ISSUE TITLE
Help : State Not Updating in ValidationInput

### ISSUE THREAD

**Issue by ImAbhishekTomar** [akveo/kittenTricks#232]
If i am updating state on calendar date change, my date value has change in state but this is not updating in InputText control. 

My Sample Code EXPO https://snack.expo.io/@abhi.tomar/inputtextstateerrorcode
_this code is not compilable because i am using lot of reference, i will sharing this for reference only._

**Reddit Discussion With GIF Demo** 
https://www.reddit.com/r/reactnative/comments/ckmu47/please_help_if_i_am_updating_state_on_calendar/?utm_source=share&utm_medium=web2x

**Comment by artyorsh** [comment]
Hi 👋 
Thanks for reporting. Unfortunately, this issue does not belong to UI Kitten, but to Kitten Triks app, so I've transferred it.

Just looked through the sources you used, and noticed [an interesting comment](https://github.com/akveo/kittenTricks/blob/master/src/components/common/validationInput.component.tsx#L29). Unfortunately, this component was designed to use in a simple forms and it updates its own state itself, so `value` prop is ignored. In your case, there should be more tricky update logic.

We're welcome to your pull request on this issue here
