### ISSUE TITLE
Not working in Expo 18

### ISSUE THREAD

**Issue by asaphaaning** [akveo/kittenTricks#26]
Used to work with Expo 17. Tried a boilerplate app, either I get a blank page or a "Could not connect to server"

**Comment by malashkevich** [comment]
Hello @ASAPHAANING.
As for now we do not support expo because of some native libraries like `realm.io`. We will probably  implement it in near future.

**Comment by vladimir-tsapkov** [comment]
Hi, @malashkevich !
Can you add support of another data provider for now? Need kittenTricks for Expo too....
Thanks!

**Comment by thelaith** [comment]
Most people that use React Native use Expo in some way or form, so hoping this will be implemented 🙏

**Comment by elgiovanno** [comment]
Hello @malashkevich. Seems to work fine in expo here: https://expo.io/@community/kitten-tricks
Curious...what steps did you need to take to make it work? Are you using something other than realm there?

**Comment by vladimir-tsapkov** [comment]
Hi, elgiovanno! In this expo example not enabled realm. It’s not supported in expo. I think it’s just commented lines, and using only json files for listing items in feed/dialogs list/ etc. Because cannot write PM and view profile or blog post from list except one. So I’m do the same - just disable realm.io using in source code, make read data from json files that used for “bootstrap” database. Also successfully added auth via fetch and real-time messaging via socket.io. If you need some help with this - feel free to ask me.

**Comment by elgiovanno** [comment]
@vladimir-tsapkov Awesome! I'll have a try at your work-around and see what I find. Any chance you have a repo that can be forked? PS sorry for late reponse, I live in puerto rico and right now it's not so easy to communicate after Hurricane Maria.

**Comment by sergey-kozel** [comment]
Hi @ASAPHAANING, @vladimir-tsapkov, @thelaith, @elgiovanno 

Kitten Tricks is at expo now:

https://expo.io/@akveo/kitten-tricks
