### ISSUE TITLE
How to handle Signin validation ?

### ISSUE THREAD

**Issue by louisiscoding** [akveo/kittenTricks#272]
## 💬 Question

In my Demo app kitten tricks, i see there is some validation on Form for Sign Auth screen.
But when i'm implementing the layout Auth-Signing 2, there is none.

It would be very interesting to see how you handle it with the styling 

## UI Kitten and Eva version

| Package      | Version |
| ----------- | ----------- |
| @eva-design/eva      |    1.4.0    |
| @ui-kitten/components   |     4.4.0    |

**Comment by artyorsh** [comment]
@LouisJS It's pretty simple with [Formik](https://github.com/jaredpalmer/formik) or [react-hook-form](https://github.com/react-hook-form/react-hook-form). Both libraries can be integrated with UI Kitten and work well. I tested it in my own production app. We're not going to include any business logic into this demo because it may lead to installing additional dependencies and a more complex way of [cloning screens](https://github.com/akveo/kittenTricks/blob/master/DEV_DOCS.md#reusing-screens) as a result.

**Comment by louisiscoding** [comment]
Could you show me an example how to reproduce the same behavior of validation in Sign in Auth 2 with react-hook-form. I do not succeed to make it work with Input from UI Kitten

That would be of great help
